version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: on-failure
        environment:
            MONGO_INITDB_ROOT_USERNAME: nttung
            MONGO_INITDB_ROOT_PASSWORD: mongodb
            MONGO_INITDB_DATABASE: shoes-shop
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro